### ISSUE TITLE
Potential import collision: import path should be "go.mongodb.org/mongo-driver", not "github.com/mongodb/mongo-go-driver"

### ISSUE THREAD

**Issue by KateGo520** [exu/go-workshops#4]
## Background
I find that `go.mongodb.org/mongo-driver` and `github.com/mongodb/mongo-go-driver` coexist in this repo：
https://github.com/exu/go-workshops/blob/master/go.mod （Line 49 & 71）
```
github.com/mongodb/mongo-go-driver v1.1.3
go.mongodb.org/mongo-driver v1.1.3 // indirect
```
That’s because the `mongodb/mongo-go-driver` has already renamed it’s import path from "github.com/mongodb/mongo-go-driver" to "go.mongodb.org/mongo-driver". When you use the old path "github.com/mongodb/mongo-go-driver" to import the `mongodb/mongo-go-driver`, will reintroduces `mongodb/mongo-go-driver` through the import statements "import go.mongodb.org/mongo-driver" in the go source file of `mongodb/mongo-go-driver`.

https://github.com/mongodb/mongo-go-driver/blob/v1.1.3/mongo/client.go#L16
```
package mongo
import (
	"go.mongodb.org/mongo-driver/bson"
	"go.mongodb.org/mongo-driver/bson/bsoncodec"
	…
)
```

The "go.mongodb.org/mongo-driver" and "github.com/mongodb/mongo-go-driver" are the same repos. This will work in isolation, bring about potential risks and problems.

## Solution
Follow the requirements of [mongodb/mongo-go-driver README.md](https://github.com/mongodb/mongo-go-driver/blob/v1.1.3/README.md):
```
To get started with the driver, import the mongo package, create a mongo.Client:

import (
    "go.mongodb.org/mongo-driver/mongo"
    "go.mongodb.org/mongo-driver/mongo/options"
)
…
```

Replace all the old import paths, change `"github.com/mongodb/mongo-go-driver"` to `"go.mongodb.org/mongo-driver"`.
Where did you import it: https://github.com/exu/go-workshops/search?q=github.com%2Fmongodb%2Fmongo-go-driver&unscoped_q=github.com%2Fmongodb%2Fmongo-go-driver

**Comment by KateGo520** [comment]
@exu  @kataras  Could you help me review this issue? Thx :p

**Comment by kataras** [comment]
Hello @KateGo520,

Of course, let me drink some coffee and start preparing a PR :)

Also, there is an example of `go.mongodb.org/mongo-driver` at: https://github.com/kataras/iris/tree/master/_examples/database/mongodb as well.

**Comment by kataras** [comment]
It's done at https://github.com/exu/go-workshops/pull/5 :)

**Comment by KateGo520** [comment]
@kataras   I see the latest commit. Thank you for your contribution!

**Comment by kataras** [comment]
Welcome @KateGo520 , always!
